if: tag IS blank

os:
  - linux
  - osx
  - windows
compiler:
  - gcc
  - clang
env:
  - TINYSPLINE_FLOAT_PRECISION=OFF
  - TINYSPLINE_FLOAT_PRECISION=ON

language: cpp
dist: bionic
sudo: true
osx_image: xcode11

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update && sudo apt-get install -y cmake; fi;
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install cmake && choco install swig; fi;

script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ] && [ "$CC" == "gcc" ]; then cmake -G "Visual Studio 15 2017" -A Win32 .; fi;
  - if [ "$TRAVIS_OS_NAME" == "windows" ] && [ "$CC" == "clang" ]; then cmake -G "Visual Studio 15 2017" -A x64 .; fi;
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cmake .; fi;
  - cmake --build .
  - cmake --build . --target tests

jobs:
  include:
    - stage: Deploy Binaries (Linux Docker)
      services: docker
      install: skip
      script:
        - pushd tools/ci
        - ./build.linux-x86_64.sh
        - ./build.macosx-x86_64.sh
        - ./bundle.sh
        - popd
      before_deploy:
        - git tag -f snapshot
        - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git push -f gh snapshot
        - git remote remove gh
      deploy:
        - provider: releases
          api-key: $GITHUB_TOKEN
          skip_cleanup: true
          file_glob: true
          file: tools/ci/tinyspline/*
          name: Snapshot build
          prerelease: true
          overwrite: true
          target_commitish: $TRAVIS_COMMIT
          on:
            branch: master
    - stage: Deploy Documentation
      service: docker
      install: skip
      script:
        - pushd tools/ci
        - ./build.docs.sh
        - popd
      deploy:
        - provider: pages
          github_token: $GITHUB_TOKEN
          skip_cleanup: true
          local_dir: tools/ci/build.docs/html
          on:
            branch: master
