if: tag IS blank
branches:
  except:
    - travis-storage

language: cpp
dist: bionic
sudo: true
osx_image: xcode11

os:
  - linux
  - osx
  - windows
compiler:
  - gcc
  - clang
env:
  - TINYSPLINE_FLOAT_PRECISION=OFF
  - TINYSPLINE_FLOAT_PRECISION=ON

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update && sudo apt-get install -y cmake; fi;
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install cmake; fi;
script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ] && [ "$CC" == "gcc" ]; then cmake -G "Visual Studio 15 2017" -A Win32 .; fi;
  - if [ "$TRAVIS_OS_NAME" == "windows" ] && [ "$CC" == "clang" ]; then cmake -G "Visual Studio 15 2017" -A x64 .; fi;
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cmake .; fi;
  - cmake --build .
  - cmake --build . --target tests

jobs:
  include:
    - stage: Deploy Binaries (Windows VM)
      os: windows
      install:
        - choco install cmake
        - choco install swig
        - choco install python3
        - C:\\Python37\\python -m pip install -U pip setuptools
        - C:\\Python37\\python -m pip install wheel
      script:
        - mkdir python3
        - pushd python3
        - cmake -G "Visual Studio 15 2017" -A x64 -DTINYSPLINE_ENABLE_PYTHON=True ..
        - C:\\Python37\\python setup.py bdist_wheel
        - popd
        - git config user.name "Travis CI"
        - git config user.email "travis@tinyspline.org"
        - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git branch -D travis-storage >/dev/null 2>&1 || true
        - git checkout --orphan travis-storage
        - cp python3/dist/tinyspline*.whl ./
        - git add tinyspline*.whl
        - git commit tinyspline*.whl -m "Windows build for ${TRAVIS_COMMIT}"
        - git push -f gh travis-storage >/dev/null 2>&1
        - git remote remove gh
    - stage: Deploy Binaries (Linux Docker)
      services: docker
      install: skip
      script:
        - pushd tools/ci
        - ./build.linux-x86_64.sh
        - ./build.macosx-x86_64.sh
        - ./bundle.sh
        - popd
      before_deploy:
        - git tag -f snapshot
        - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git push -f gh snapshot >/dev/null 2>&1
        - git fetch gh >/dev/null 2>&1
        - pushd tools/ci/tinyspline
        - git checkout gh/travis-storage tinyspline*.whl
        - popd
        - git remote remove gh
      deploy:
        - provider: releases
          api-key: $GITHUB_TOKEN
          skip_cleanup: true
          file_glob: true
          file: tools/ci/tinyspline/*
          name: Snapshot build
          prerelease: true
          overwrite: true
          target_commitish: $TRAVIS_COMMIT
          on:
            branch: master
    - stage: Deploy Website
      service: docker
      install: skip
      script:
        - pushd tools/ci
        - ./build.docs.sh
        - popd
      deploy:
        - provider: pages
          github_token: $GITHUB_TOKEN
          skip_cleanup: true
          local_dir: tools/ci/build.docs/html
          on:
            branch: master
