name: CI

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        shared: [On, Off]
        float: [On, Off]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=${{ matrix.shared }} -DTINYSPLINE_FLOAT_PRECISION=${{ matrix.float }}

    - name: Configure Installation
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
            cmake -DCMAKE_INSTALL_PREFIX=~/tinyspline -DTINYSPLINE_INSTALL_LIBRARY_DIR=lib .
        elif [ "$RUNNER_OS" == "Windows" ]; then
            cmake -DCMAKE_INSTALL_PREFIX=C:/tinyspline -DTINYSPLINE_INSTALL_LIBRARY_DIR=lib .
        else
            cmake -DCMAKE_INSTALL_PREFIX=~/tinyspline .
        fi

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

    - name: Install
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --target install

    - name: Test CMake Installation
      shell: bash
      run: |
        mkdir $GITHUB_WORKSPACE/test/pkg/build
        cd $GITHUB_WORKSPACE/test/pkg/build
        if [ "$RUNNER_OS" == "Windows" ]; then
            cmake -DCMAKE_PREFIX_PATH=C:/tinyspline ..
        else
            cmake -DCMAKE_PREFIX_PATH=~/tinyspline ..
        fi
        cmake --build .
        ctest

    - name: Test Pkg-config Installation
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/test/pkg
        if [ "$RUNNER_OS" == "Linux" ]; then
            PKG_CONFIG_PATH=~/tinyspline/lib/pkgconfig make test
        elif [ "$RUNNER_OS" == "macOS" ]; then
            PKG_CONFIG_PATH=~/tinyspline/lib64/pkgconfig make test
        fi

  python:
    needs: build
    runs-on: windows-latest
    strategy:
      matrix:
        python: [2, 3]

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      shell: bash
      run: |
        choco install swig
        choco install python${{ matrix.python }}
        python -m pip install -U pip setuptools
        python -m pip install wheel

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{runner.workspace}}/python${{ matrix.python }}

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/python${{ matrix.python }}
      run: cmake $GITHUB_WORKSPACE -A x64 -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DTINYSPLINE_ENABLE_PYTHON=True -DTINYSPLINE_PYTHON_VERSION=${{ matrix.python }}

    - name: Build
      working-directory: ${{runner.workspace}}/python${{ matrix.python }}
      shell: bash
      run: python setup.py bdist_wheel
