name: CI

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        shared: [On, Off]
        float: [On, Off]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=${{ matrix.shared }} -DTINYSPLINE_FLOAT_PRECISION=${{ matrix.float }}

    - name: Configure Installation
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
            cmake -DCMAKE_INSTALL_PREFIX=~/tinyspline -DTINYSPLINE_INSTALL_LIBRARY_DIR=lib .
        elif [ "$RUNNER_OS" == "Windows" ]; then
            cmake -DCMAKE_INSTALL_PREFIX=C:/tinyspline -DTINYSPLINE_INSTALL_LIBRARY_DIR=lib .
        else
            cmake -DCMAKE_INSTALL_PREFIX=~/tinyspline .
        fi

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

    - name: Install
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --target install

    - name: Test CMake Installation
      working-directory: ${{runner.workspace}}/test/pkg
      shell: bash
      run: |
        mkdir build
        cd build
        if [ "$RUNNER_OS" == "Windows" ]; then
            cmake -DCMAKE_PREFIX_PATH=C:/tinyspline ..
        else
            cmake -DCMAKE_PREFIX_PATH=~/tinyspline ..
        fi
        cmake --build .
        ctest
